messages:
  2D: "&7Texture pack &c2D&7 click sur le lien : &6http://www.mediafire.com/file/co4iup8b5ppn36i/OpalGta_Pack_2D.zip/file"
  3D: "&7Texture pack &c3D&7 click sur le lien : &4&lMaintenance"
  pack: "&eCommandes pour acceder au pack &5&l:&6 /2D &bet &6/3D"
  config-reload: "La configuration a bien été reload !"
  no-player: "Vous devez être un joueur pour executer cette commande !"
  no-perm: "&cVous n'avez pas la permission d'executer cette commande !"
  pas-chiffre: "&c%arg1% n'est pas un chiffre !"
  cooldownchat-set: "&cVous venez de mettre le cooldownchat à %secondes% secondes."
  cooldownchat: "&dAttends un peu avant de parler!"
  GTA-dk: "&c&lGTA &ene connait pas cette commande"
  do-msg: "&c/msg <pseudo> <message>"
  nomap: "&cVous ne pouvez pas utiliser cette commande dans la map"
  clearchat: "&8&l>> &cLe chat a été clear par &b%player%"
  color: "&7&lLes couleurs: &00&11&22&33&44&55&66&77&88&99&aa&bb&cc&dd&ee&ff"
  first-join: "&eBienvenue &b%player%&e sur notre serveur &3&lGTA"
  fake-join:  "&7[&a+&7] &a%player%"
  fake-leave: "&7[&c-&7] &c%player%"
  help0: "&7/opalcraft help"
  help1: "&7/opalcraft help : Permet de voir la liste des commandes"
  help2: "&7/opalcraft reload : Permet de reload la config"
  help3: "&7/opalcraft cooldownchat <temps> : Permet de mettre un cooldown au chat"
  help4: "&7/opalcraft clearchat : Permet de clear le chat"
  impossible-interact-block: "&cImpossible d'interagir avec ce bloc"
  impossible-interact-item: "&cInterdit"
  impossible-interact-button: "&8&l>> &eNope ;)"

cooldownchat:
  time: 3

mobs:
  zombie-name: "§bPolice"
  skeleton-name: "§cSwat"

permissions:
  opalcraft-command: "opalcraft.command.use"
  cooldownchat: "opalcraft.cooldownchat.use"
  cooldownchat-bypass: "opalcraft.cooldownchat.bypass"
  clearchat: "opalcraft.clearchat.use"
  chestinteract: "opalcraft.chest.interact"
  fakejoin: "opalcraft.fake.join"
  fakeleave: "opalcraft.fake.leave"